#!/usr/bin/env python3
"""Generate Python dataclasses from the Cepage OpenAPI 3.1 spec.

Usage::

    python scripts/generate-python-sdk-types.py

Environment variables:
    OPENAPI_SPEC_PATH – Local file path to read the spec from (default:
                        ../../sdk/.openapi-cache.json)
"""
from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any


_SPEC_RELPATH = Path("..") / ".." / "sdk" / ".openapi-cache.json"
_HEADER = "# Auto-generated by scripts/generate-python-sdk-types.py"


def _to_snake_case(name: str) -> str:
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def _ref_to_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _schema_to_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return _ref_to_name(schema["$ref"])

    if "oneOf" in schema or "anyOf" in schema:
        alts = schema.get("oneOf") or schema.get("anyOf") or []
        types = []
        for alt in alts:
            if alt.get("type") == "null":
                types.append("None")
            else:
                types.append(_schema_to_type(alt))
        # deduplicate while preserving order
        seen: set[str] = set()
        uniq: list[str] = []
        for t in types:
            if t not in seen:
                seen.add(t)
                uniq.append(t)
        if len(uniq) == 1:
            return uniq[0]
        return " | ".join(uniq)

    nullable = schema.get("nullable", False)
    stype = schema.get("type")

    if stype == "string":
        base = "str"
    elif stype == "integer":
        base = "int"
    elif stype == "number":
        base = "float"
    elif stype == "boolean":
        base = "bool"
    elif stype == "array":
        items = schema.get("items", {})
        item_type = _schema_to_type(items)
        base = f"list[{item_type}]"
    elif stype == "object":
        base = "dict[str, Any]"
    elif stype is None:
        base = "Any"
    else:
        base = "Any"

    if nullable and base != "None":
        return f"{base} | None"
    return base


def _is_ref_union(schema: dict[str, Any]) -> bool:
    if "oneOf" in schema or "anyOf" in schema:
        alts = schema.get("oneOf") or schema.get("anyOf") or []
        non_null = [a for a in alts if a.get("type") != "null"]
        return len(non_null) == 1 and "$ref" in non_null[0]
    return False


def _ref_from_union(schema: dict[str, Any]) -> str | None:
    if _is_ref_union(schema):
        alts = schema.get("oneOf") or schema.get("anyOf") or []
        non_null = [a for a in alts if a.get("type") != "null"]
        return _ref_to_name(non_null[0]["$ref"])
    return None


def _build_from_dict_field(prop_name: str, py_name: str, schema: dict[str, Any], *, required: bool) -> str:
    if "$ref" in schema:
        ref_name = _ref_to_name(schema["$ref"])
        if required:
            return f"        {py_name} = {ref_name}.from_dict(data.get(\"{prop_name}\", {{}}))"
        return (
            f"        {py_name}_raw = data.get(\"{prop_name}\")\n"
            f"        {py_name} = {ref_name}.from_dict({py_name}_raw) "
            f"if isinstance({py_name}_raw, dict) else None"
        )

    ref_name = _ref_from_union(schema)
    if ref_name is not None:
        if required:
            return f"        {py_name} = {ref_name}.from_dict(data.get(\"{prop_name}\", {{}}))"
        return (
            f"        {py_name}_raw = data.get(\"{prop_name}\")\n"
            f"        {py_name} = {ref_name}.from_dict({py_name}_raw) "
            f"if isinstance({py_name}_raw, dict) else None"
        )

    stype = schema.get("type")

    if stype == "array":
        items = schema.get("items", {})
        if "$ref" in items:
            item_ref = _ref_to_name(items["$ref"])
            return (
                f"        {py_name} = [{item_ref}.from_dict(i) for i in "
                f"(data.get(\"{prop_name}\") or [])] "
                f"if isinstance(data.get(\"{prop_name}\"), list) else []"
            )
        itype = items.get("type")
        if itype == "string":
            cast = "str"
        elif itype == "integer":
            cast = "int"
        elif itype == "number":
            cast = "float"
        elif itype == "boolean":
            cast = "bool"
        else:
            cast = ""
        if cast:
            return (
                f"        {py_name} = [{cast}(i) for i in "
                f"(data.get(\"{prop_name}\") or [])] "
                f"if isinstance(data.get(\"{prop_name}\"), list) else []"
            )
        return (
            f"        {py_name} = list(data.get(\"{prop_name}\", []) or []) "
            f"if isinstance(data.get(\"{prop_name}\"), list) else []"
        )

    if stype == "string":
        default = _python_string(schema.get("default", ""))
        if required:
            return f"        {py_name} = str(data.get(\"{prop_name}\", {default}))"
        return f"        {py_name} = data.get(\"{prop_name}\")"

    if stype == "integer":
        default = schema.get("default", 0)
        if required:
            return f"        {py_name} = int(data.get(\"{prop_name}\", {default}))"
        return f"        {py_name} = data.get(\"{prop_name}\")"

    if stype == "number":
        default = schema.get("default", 0)
        if required:
            return f"        {py_name} = float(data.get(\"{prop_name}\", {default}))"
        return f"        {py_name} = data.get(\"{prop_name}\")"

    if stype == "boolean":
        default = "True" if schema.get("default", False) else "False"
        if required:
            return f"        {py_name} = bool(data.get(\"{prop_name}\", {default}))"
        return f"        {py_name} = data.get(\"{prop_name}\")"

    if stype == "object":
        if required:
            return f"        {py_name} = dict(data.get(\"{prop_name}\", {{}}) or {{}})"
        return f"        {py_name} = data.get(\"{prop_name}\")"

    if required:
        return f"        {py_name} = data.get(\"{prop_name}\", {{}})"
    return f"        {py_name} = data.get(\"{prop_name}\")"


def _python_string(value: str) -> str:
    """Return a Python string literal representation."""
    return repr(value)


def _build_to_dict_field(prop_name: str, py_name: str, schema: dict[str, Any], *, required: bool) -> str:
    """Return Python source line(s) that serialize ``self.py_name`` into ``result[prop_name]``."""
    if "$ref" in schema or _is_ref_union(schema):
        lines = [
            f'        if self.{py_name} is not None:',
            f'            result["{prop_name}"] = self.{py_name}.to_dict()',
        ]
        return "\n".join(lines)

    stype = schema.get("type")

    if stype == "array":
        items = schema.get("items", {})
        if "$ref" in items:
            return f'        result["{prop_name}"] = [i.to_dict() for i in self.{py_name}]'
        return f'        result["{prop_name}"] = list(self.{py_name})'

    if stype == "object":
        lines = [
            f'        if self.{py_name} is not None:',
            f'            result["{prop_name}"] = dict(self.{py_name})',
        ]
        return "\n".join(lines)

    return f'        result["{prop_name}"] = self.{py_name}'


def _generate_dataclass(name: str, schema: dict[str, Any]) -> str:
    lines: list[str] = []
    lines.append("@dataclass")
    lines.append(f"class {name}:")
    lines.append('    """Auto-generated dataclass."""')

    props = schema.get("properties", {})
    required = set(schema.get("required", []))

    fields: list[str] = []
    for prop_name, prop_schema in props.items():
        py_name = _to_snake_case(prop_name)
        py_type = _schema_to_type(prop_schema)

        if prop_name in required:
            fields.append(f"    {py_name}: {py_type}")
        else:
            if py_type.startswith("list["):
                fields.append(f"    {py_name}: {py_type} = field(default_factory=list)")
            elif py_type == "dict[str, Any]":
                fields.append(f"    {py_name}: {py_type} = field(default_factory=dict)")
            elif py_type.endswith(" | None"):
                fields.append(f"    {py_name}: {py_type} = None")
            else:
                fields.append(f"    {py_name}: {py_type} | None = None")

    if not fields:
        fields.append("    pass")

    lines.extend(fields)
    lines.append("")
    lines.append("    @classmethod")
    lines.append(f"    def from_dict(cls, data: dict[str, Any]) -> Self:")
    lines.append('        if not isinstance(data, dict):')
    lines.append('            raise TypeError("expected dict")')

    for prop_name, prop_schema in props.items():
        py_name = _to_snake_case(prop_name)
        conversion = _build_from_dict_field(
            prop_name, py_name, prop_schema, required=prop_name in required
        )
        lines.append(conversion)

    lines.append("        return cls(")
    for prop_name, _prop_schema in props.items():
        py_name = _to_snake_case(prop_name)
        lines.append(f"            {py_name}={py_name},")
    lines.append("        )")

    # to_dict
    lines.append("")
    lines.append("    def to_dict(self) -> dict[str, Any]:")
    lines.append("        result: dict[str, Any] = {}")
    for prop_name, prop_schema in props.items():
        py_name = _to_snake_case(prop_name)
        serialization = _build_to_dict_field(
            prop_name, py_name, prop_schema, required=prop_name in required
        )
        lines.append(serialization)
    lines.append("        return result")

    return "\n".join(lines)


def _write_module(schemas: dict[str, dict[str, Any]], out_path: Path) -> None:
    lines: list[str] = []
    lines.append(_HEADER)
    lines.append("")
    lines.append('"""Auto-generated dataclasses from the Cepage OpenAPI 3.1 spec."""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("import sys")
    lines.append("from dataclasses import dataclass, field")
    lines.append("from typing import Any")
    lines.append("")
    lines.append('if sys.version_info >= (3, 11):')
    lines.append('    from typing import Self')
    lines.append('else:')
    lines.append('    from typing_extensions import Self')
    lines.append("")
    lines.append("")

    for name in sorted(schemas):
        if not (name.endswith("Inputs") or name.endswith("Outputs")):
            continue
        schema = schemas[name]
        if schema.get("type") != "object":
            continue
        lines.append(_generate_dataclass(name, schema))
        lines.append("")
        lines.append("")

    # __all__
    exported = sorted(
        name for name in schemas
        if (name.endswith("Inputs") or name.endswith("Outputs"))
        and schemas[name].get("type") == "object"
    )
    lines.append("__all__ = [")
    for name in exported:
        lines.append(f'    "{name}",')
    lines.append("]")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")
    print(f"Generated {out_path} ({len(exported)} classes)")


def main() -> None:
    default_spec = Path(__file__).resolve().parents[2] / "sdk" / ".openapi-cache.json"
    spec_path_str = os.environ.get("OPENAPI_SPEC_PATH") or str(default_spec)
    spec_path = Path(spec_path_str).resolve()

    if not spec_path.exists():
        raise FileNotFoundError(f"OpenAPI spec not found: {spec_path}")

    spec = json.loads(spec_path.read_text())
    schemas = spec.get("components", {}).get("schemas", {})

    out_path = Path(__file__).resolve().parents[1] / "cepage" / "generated_types.py"
    _write_module(schemas, out_path)


if __name__ == "__main__":
    main()
